/**
 * QCM additionnels : densifier chaque bandeau (langues A/B/C · Primaire/Collège/Lycée).
 * Upsert ids uniques ; à fusionner dans le seed principal.
 */
import type { SeedCatalogQcm } from "./seed-catalog-quizzes";

export const FILL_CATALOG_SEED_QCMS: SeedCatalogQcm[] = [
  // ——— Langues : 2e quiz par niveau A (×6) ———
  {
    id: "seed-fill-fr-a",
    title: "Français — Niveau A · déterminants et présent",
    matiere: "Français",
    niveau: "A",
    chapitre: "Articles · présent du 1er groupe",
    questions: [
      { id: "ffa1", prompt: "« ___ fille lit » (voyelle, féminin sing.) :", options: ["Le", "La", "Les"], correct: 1 },
      { id: "ffa2", prompt: "« Nous ___ en classe » (être, présent) :", options: ["sommes", "êtes", "sont"], correct: 0 },
      { id: "ffa3", prompt: "« Il ___ un livre » (avoir) :", options: ["a", "as", "ont"], correct: 0 },
      { id: "ffa4", prompt: "Masculin sing. devant consonne : « ___ professeur » :", options: ["Le", "La", "L’"], correct: 0 },
      { id: "ffa5", prompt: "Pluriel : « ___ enfants jouent » :", options: ["Le", "La", "Les"], correct: 2 },
    ],
  },
  {
    id: "seed-fill-es-a",
    title: "Espagnol — Niveau A · présent regulier -ar",
    matiere: "Espagnol",
    niveau: "A",
    chapitre: "Verbes en -ar",
    questions: [
      { id: "efa1", prompt: "« Yo ___ español » (hablar) :", options: ["hablo", "hablas", "hablan"], correct: 0 },
      { id: "efa2", prompt: "« Tú ___ en el parque » (caminar) :", options: ["caminamos", "caminas", "camina"], correct: 1 },
      { id: "efa3", prompt: "« Ellos ___ mucho » (estudiar) :", options: ["estudio", "estudias", "estudian"], correct: 2 },
      { id: "efa4", prompt: "« La niña ___ agua » (beber → -er, attention) :", options: ["bebo", "bebes", "bebe"], correct: 2 },
      { id: "efa5", prompt: "Négation simple : « No ___ » (yo / ir) :", options: ["voy", "vas", "va"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-en-a",
    title: "Anglais — Niveau A · verbe to be",
    matiere: "Anglais",
    niveau: "A",
    chapitre: "To be · pronouns",
    questions: [
      { id: "ena1", prompt: "« I ___ a student » :", options: ["am", "is", "are"], correct: 0 },
      { id: "ena2", prompt: "« They ___ friends » :", options: ["am", "is", "are"], correct: 2 },
      { id: "ena3", prompt: "« She ___ from Morocco » :", options: ["am", "is", "are"], correct: 1 },
      { id: "ena4", prompt: "« We ___ not tired » :", options: ["am", "is", "are"], correct: 2 },
      { id: "ena5", prompt: "« ___ you OK? » (sing.) :", options: ["Am", "Is", "Are"], correct: 2 },
    ],
  },
  {
    id: "seed-fill-enus-a",
    title: "Anglais américain — Niveau A · greetings",
    matiere: "Anglais américain",
    niveau: "A",
    chapitre: "Salutations · temps",
    questions: [
      { id: "eua1", prompt: "« How’s it ___? » (familier US) :", options: ["going", "go", "gone"], correct: 0 },
      { id: "eua2", prompt: "« See you ___! » (à plus tard) :", options: ["later", "lately", "latest"], correct: 0 },
      { id: "eua3", prompt: "« You’re ___! » (bienvenue) :", options: ["welcome", "welcoming", "welcomed"], correct: 0 },
      { id: "eua4", prompt: "« Have a good ___! » (journée) :", options: ["day", "way", "say"], correct: 0 },
      { id: "eua5", prompt: "« I’m good, ___ you » :", options: ["thank", "thanks", "thank you"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-de-a",
    title: "Allemand — Niveau A · sein / présent régulier",
    matiere: "Allemand",
    niveau: "A",
    chapitre: "sein · verbes faibles",
    questions: [
      { id: "dea1", prompt: "« Ich ___ müde » :", options: ["bin", "bist", "ist"], correct: 0 },
      { id: "dea2", prompt: "« Du ___ nett » :", options: ["bin", "bist", "sind"], correct: 1 },
      { id: "dea3", prompt: "« Wir ___ Freunde » :", options: ["bin", "bist", "sind"], correct: 2 },
      { id: "dea4", prompt: "« Er ___ Deutsch » (lernen, 3e sing.) :", options: ["lerne", "lernst", "lernt"], correct: 2 },
      { id: "dea5", prompt: "« Das ___ ein Buch » :", options: ["bin", "ist", "sind"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-zh-a",
    title: "Chinois — Niveau A · nombres et formules de politesse",
    matiere: "Chinois (mandarin)",
    niveau: "A",
    chapitre: "Chiffres · saluts",
    questions: [
      { id: "zha1", prompt: "« 五 » se lit (pinyin courant) :", options: ["wǔ", "liù", "sì"], correct: 0 },
      { id: "zha2", prompt: "« 谢谢 » signifie :", options: ["bonjour", "merci", "au revoir"], correct: 1 },
      { id: "zha3", prompt: "« 四 » (chiffre) :", options: ["2", "4", "10"], correct: 1 },
      { id: "zha4", prompt: "« 早上好 » convient pour :", options: ["le soir", "le matin", "les adieux"], correct: 1 },
      { id: "zha5", prompt: "« 零 » évoque le plus souvent :", options: ["dix", "zéro", "cent"], correct: 1 },
    ],
  },

  // ——— Langues : 2e quiz par niveau B (×6) ———
  {
    id: "seed-fill-fr-b",
    title: "Français — Niveau B · futur proche et COD",
    matiere: "Français",
    niveau: "B",
    chapitre: "aller + infinitif · COD",
    questions: [
      { id: "ffb1", prompt: "« Je ___ manger » (futur proche) :", options: ["vais", "vas", "vont"], correct: 0 },
      { id: "ffb2", prompt: "« Elle ___ voir un film » :", options: ["va", "vas", "allons"], correct: 0 },
      { id: "ffb3", prompt: "« J’aime ___ film » (déterminant démonstratif masculin) :", options: ["ce", "cette", "ces"], correct: 0 },
      { id: "ffb4", prompt: "« Je ___ connais » (COD masculin sing. devant voyelle) :", options: ["le", "l’", "en"], correct: 1 },
      { id: "ffb5", prompt: "« Nous ___ du théâtre samedi » (aller, 1re pl.) :", options: ["allons", "allez", "vont"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-es-b",
    title: "Espagnol — Niveau B · gustar + quantificateurs",
    matiere: "Espagnol",
    niveau: "B",
    chapitre: "Me gusta · mucho/poco",
    questions: [
      { id: "efb1", prompt: "« ___ gusta el chocolate » :", options: ["Me", "Te", "Le"], correct: 0 },
      { id: "efb2", prompt: "« Nos ___ los deportes » :", options: ["gusta", "gustan", "gusto"], correct: 1 },
      { id: "efb3", prompt: "« No ___ estudiar hoy » (querer, yo) :", options: ["quiero", "quieres", "quiere"], correct: 0 },
      { id: "efb4", prompt: "« Hay ___ tiempo » (peu) :", options: ["mucho", "poco", "muchos"], correct: 1 },
      { id: "efb5", prompt: "« Ellos ___ cansados » :", options: ["está", "están", "estamos"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-en-b",
    title: "Anglais — Niveau B · preterit régulier",
    matiere: "Anglais",
    niveau: "B",
    chapitre: "Past simple -ed",
    questions: [
      { id: "enb1", prompt: "« She ___ TV yesterday » (watch) :", options: ["watch", "watched", "watching"], correct: 1 },
      { id: "enb2", prompt: "« They ___ to school on foot » (walk) :", options: ["walked", "walk", "walking"], correct: 0 },
      { id: "enb3", prompt: "« I ___ not agree » (past, do support) :", options: ["did", "do", "does"], correct: 0 },
      { id: "enb4", prompt: "« We ___ dinner at 7 » (have) :", options: ["had", "have", "has"], correct: 0 },
      { id: "enb5", prompt: "« Did you ___ the news? » :", options: ["see", "saw", "seen"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-enus-b",
    title: "Anglais américain — Niveau B · modaux courants",
    matiere: "Anglais américain",
    niveau: "B",
    chapitre: "Can / should / must (light)",
    questions: [
      { id: "eub1", prompt: "« You ___ wear a seat belt » (règle) :", options: ["can", "should", "may"], correct: 1 },
      { id: "eub2", prompt: "« ___ I borrow your pen? » :", options: ["Can", "Should", "Must"], correct: 0 },
      { id: "eub3", prompt: "« He ___ speak three languages » (capacité) :", options: ["should", "can", "must"], correct: 1 },
      { id: "eub4", prompt: "« We ___ hurry or we’ll be late » :", options: ["can’t", "must", "could"], correct: 1 },
      { id: "eub5", prompt: "« You ___ not smoke here » :", options: ["can", "should", "must"], correct: 2 },
    ],
  },
  {
    id: "seed-fill-de-b",
    title: "Allemand — Niveau B · Akkusativ déterminé",
    matiere: "Allemand",
    niveau: "B",
    chapitre: "Cas accusatif · définis",
    questions: [
      { id: "deb1", prompt: "« Ich sehe ___ Hund » (masc., défini A.) :", options: ["der", "den", "dem"], correct: 1 },
      { id: "deb2", prompt: "« Er kauft ___ Zeitung » (féminin A.) :", options: ["die", "der", "den"], correct: 0 },
      { id: "deb3", prompt: "« Wir essen ___ Brot » (neutre A.) :", options: ["das", "dem", "den"], correct: 0 },
      { id: "deb4", prompt: "« Ich gebe ___ Mann das Buch » (Dativ masc. « au » homme) :", options: ["der", "den", "dem"], correct: 2 },
      { id: "deb5", prompt: "« Sie hat ___ Tasche » (féminin A. indéfini) :", options: ["einen", "eine", "ein"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-zh-b",
    title: "Chinois — Niveau B · temps et lieu simples",
    matiere: "Chinois (mandarin)",
    niveau: "B",
    chapitre: "今天 · 在",
    questions: [
      { id: "zhb1", prompt: "« 昨天 » signifie :", options: ["demain", "hier", "aujourd’hui"], correct: 1 },
      { id: "zhb2", prompt: "« 我在学校 » signifie environ :", options: ["je suis à l’école", "je vais à la maison", "je mange"], correct: 0 },
      { id: "zhb3", prompt: "« 明天 » signifie :", options: ["hier", "demain", "midi"], correct: 1 },
      { id: "zhb4", prompt: "« 朋友 » signifie souvent :", options: ["professeur", "ami", "livre"], correct: 1 },
      { id: "zhb5", prompt: "« 你叫什么名字？ » demande en général :", options: ["l’âge", "le nom", "l’heure"], correct: 1 },
    ],
  },

  // ——— Langues : 3e quiz par niveau C (×6) ———
  {
    id: "seed-fill-fr-c",
    title: "Français — Niveau C · concordance participe / passif",
    matiere: "Français",
    niveau: "C",
    chapitre: "Accord du participe · tournures",
    questions: [
      { id: "ffc1", prompt: "« Les lettres qu’elle ___ » (écrire, féminin pluriel) :", options: ["a écrites", "a écrit", "ont écrit"], correct: 0 },
      { id: "ffc2", prompt: "« La porte est ___ par le gardien » (ouvrir) :", options: ["ouverte", "ouvert", "ouverts"], correct: 0 },
      { id: "ffc3", prompt: "« Elles se sont ___ » (rendre compte, féminin) :", options: ["rendu compte", "rendues compte", "rendues comptes"], correct: 0 },
      { id: "ffc4", prompt: "« Il faut qu’il ___ plus patient » (subjonctif être) :", options: ["soit", "est", "était"], correct: 0 },
      { id: "ffc5", prompt: "« Peu importe qu’il ___ en retard » (indicatif fréquent dans l’usage familier — ici indicatif) :", options: ["soit", "est", "fût"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-es-c",
    title: "Espagnol — Niveau C · plus-que-parfait / discours rapporté (repères)",
    matiere: "Espagnol",
    niveau: "C",
    chapitre: "Plus-que-parfait",
    questions: [
      { id: "efc1", prompt: "« Ya ___ comido cuando llegaste » (él / haber) :", options: ["había", "había", "ha"], correct: 0 },
      { id: "efc2", prompt: "« Si ___ rico, viajaría más » (ser, imperfecto subj.) :", options: ["fuera", "fue", "sea"], correct: 0 },
      { id: "efc3", prompt: "« Ojalá ___ tiempo » (tener, présent subj. 1re sing.) :", options: ["tenga", "tengo", "tendré"], correct: 0 },
      { id: "efc4", prompt: "« No creo que ___ verdad » (ser) :", options: ["es", "sea", "era"], correct: 1 },
      { id: "efc5", prompt: "« Antes ___ en Madrid » (vivir, imperfecto) :", options: ["vivía", "vivió", "he vivido"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-en-c",
    title: "Anglais — Niveau C · mixed conditionals / inversion (repères)",
    matiere: "Anglais",
    niveau: "C",
    chapitre: "Conditionnels · style",
    questions: [
      { id: "enc1", prompt: "« Had I known, I ___ you » :", options: ["would tell", "would have told", "tell"], correct: 1 },
      { id: "enc2", prompt: "« Not only ___ he arrive late, but he forgot the file » :", options: ["did", "does", "has"], correct: 0 },
      { id: "enc3", prompt: "« I wish I ___ harder last year » :", options: ["study", "had studied", "studied"], correct: 1 },
      { id: "enc4", prompt: "« It’s time we ___ home » :", options: ["go", "went", "going"], correct: 1 },
      { id: "enc5", prompt: "« Were she here, she ___ agree » :", options: ["will", "would", "can"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-enus-c",
    title: "Anglais américain — Niveau C · style formel / reductions orales",
    matiere: "Anglais américain",
    niveau: "C",
    chapitre: "Registre · reductions",
    questions: [
      { id: "euc1", prompt: "« Could you possibly ___ me a moment? » :", options: ["spare", "spared", "sparing"], correct: 0 },
      { id: "euc2", prompt: "Oral US « gonna » ≈ :", options: ["going to", "gone to", "went to"], correct: 0 },
      { id: "euc3", prompt: "« I’d appreciate it if you ___ quiet » :", options: ["stay", "stayed", "had stayed"], correct: 1 },
      { id: "euc4", prompt: "« The report, ___, was incomplete » :", options: ["however", "whatever", "whoever"], correct: 0 },
      { id: "euc5", prompt: "« He’s got no idea what she’s ___ about » :", options: ["talking", "talk", "talked"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-de-c",
    title: "Allemand — Niveau C · Konjunktiv II / Konditionalsätze (repères)",
    matiere: "Allemand",
    niveau: "C",
    chapitre: "Konjunktiv II · si-clauses",
    questions: [
      { id: "dec1", prompt: "« Wenn ich Zeit ___, käme ich » :", options: ["hätte", "habe", "hatte"], correct: 0 },
      { id: "dec2", prompt: "« Es wäre besser, du ___ pünktlich » (sein) :", options: ["wärst", "bist", "warst"], correct: 0 },
      { id: "dec3", prompt: "« An deiner Stelle ___ ich nicht » (gehen, Konj. II) :", options: ["ginge", "gehe", "gegangen"], correct: 0 },
      { id: "dec4", prompt: "« Ohne deine Hilfe ___ wir verloren » (irréel / conseil) :", options: ["wären", "waren", "sind"], correct: 0 },
      { id: "dec5", prompt: "« Als ob er nichts ___ » (wissen) :", options: ["wüsste", "weiß", "wusste"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-zh-c",
    title: "Chinois — Niveau C · 把 / 被 (repères)",
    matiere: "Chinois (mandarin)",
    niveau: "C",
    chapitre: "Construction 把 · passif 被",
    questions: [
      { id: "zhc1", prompt: "« 我把书放在桌子上 » décrit en général :", options: ["j’ai mis le livre sur la table (disposition 把)", "je ne lis pas", "il pleut"], correct: 0 },
      { id: "zhc2", prompt: "« 被 » dans « 他被老师批评了 » suggère souvent :", options: ["passif / subir l’action", "futur seul", "négation pure"], correct: 0 },
      { id: "zhc3", prompt: "« 虽然…可是… » exprime souvent :", options: ["concession", "cause uniquement", "lieu"], correct: 0 },
      { id: "zhc4", prompt: "« 无论…都… » renforce l’idée de :", options: ["quelle que soit la condition", "interdiction", "nombre exact"], correct: 0 },
      { id: "zhc5", prompt: "« 越来越 » marque souvent :", options: ["degré croissant", "égalité", "passé accompli seul"], correct: 0 },
    ],
  },

  // ——— Tronc commun : 2e quiz par bandeau souvent à 1 seul ———
  {
    id: "seed-fill-math-primaire",
    title: "Mathématiques — Primaire · périmètres et lectures graphiques",
    matiere: "Mathématiques",
    niveau: "Primaire",
    chapitre: "Mesures · lecture",
    questions: [
      { id: "mp1", prompt: "Périmètre d’un rectangle L=8 m, l=3 m :", options: ["11 m", "22 m", "24 m"], correct: 1 },
      { id: "mp2", prompt: "3,5 h = combien de minutes :", options: ["210 min", "35 min", "350 min"], correct: 0 },
      { id: "mp3", prompt: "Un angle droit mesure :", options: ["45°", "90°", "180°"], correct: 1 },
      { id: "mp4", prompt: "Le symbole « < » signifie :", options: ["égal", "strictement plus petit", "plus grand"], correct: 1 },
      { id: "mp5", prompt: "1 km =", options: ["100 m", "1000 m", "10 m"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-phy-primaire",
    title: "Physique-Chimie — Primaire · air et eau",
    matiere: "Physique-Chimie",
    niveau: "Primaire",
    chapitre: "États · mélanges",
    questions: [
      { id: "pp1", prompt: "L’air est :", options: ["un corps pur unique", "un mélange de gaz", "un métal"], correct: 1 },
      { id: "pp2", prompt: "La glace est le solide de :", options: ["le fer", "l’eau", "l’huile"], correct: 1 },
      { id: "pp3", prompt: "Dissoudre du sel dans l’eau donne :", options: ["un mélange homogène (solution)", "toujours un gaz", "rien"], correct: 0 },
      { id: "pp4", prompt: "À pression ambiante, l’eau bout vers :", options: ["0 °C", "100 °C", "50 °C toujours exact"], correct: 1 },
      { id: "pp5", prompt: "Un aimant attire surtout :", options: ["le bois", "certains métaux (ex. fer)", "le plastique"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-svt-primaire",
    title: "SVT — Primaire · plante et milieu",
    matiere: "SVT",
    niveau: "Primaire",
    chapitre: "Végétal · lumière",
    questions: [
      { id: "sp1", prompt: "Les feuilles vertes captent surtout :", options: ["la lumière", "l’acier", "le pétrole"], correct: 0 },
      { id: "sp2", prompt: "Les racines puisent souvent :", options: ["l’eau et des sels", "l’ozone pur", "la lave"], correct: 0 },
      { id: "sp3", prompt: "Un herbivore mange surtout :", options: ["d’autres carnivores", "des végétaux", "des roches"], correct: 1 },
      { id: "sp4", prompt: "Le dioxygène O₂ est important pour :", options: ["la respiration de nombreux êtres", "refroidir le soleil", "solidifier l’eau"], correct: 0 },
      { id: "sp5", prompt: "Une fleur peut servir à :", options: ["la reproduction de la plante", "produire du pétrole", "attirer uniquement le fer"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-hg-primaire",
    title: "Histoire-Géographie — Primaire · paysage et espace local",
    matiere: "Histoire-Géographie",
    niveau: "Primaire",
    chapitre: "Territoire · relief",
    questions: [
      { id: "hp1", prompt: "Une montagne se distingue par :", options: ["une altitude relative élevée", "l’absence de roche", "la présence obligatoire d’océan"], correct: 0 },
      { id: "hp2", prompt: "Une rivière se jette souvent dans :", options: ["une école", "un fleuve, lac ou mer", "une autoroute"], correct: 1 },
      { id: "hp3", prompt: "Une carte Topographique montre surtout :", options: ["le relief et points remarquables", "la météo minute par minute", "les votes"], correct: 0 },
      { id: "hp4", prompt: "La rose des vents indique :", options: ["les directions", "les prix", "les minutes"], correct: 0 },
      { id: "hp5", prompt: "Un habitat rural évoque plutôt :", options: ["une campagne / petites agglomérations", "un hypercentre seul", "l’espace"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-phy-college",
    title: "Physique-Chimie — Collège · circuit électrique série",
    matiere: "Physique-Chimie",
    niveau: "Collège",
    chapitre: "Courant · tension",
    questions: [
      { id: "pc1", prompt: "En série, l’intensité est :", options: ["la même partout (loi des nœuds simplifiée)", "toujours nulle", "plus forte en sortie de pile sans raison"], correct: 0 },
      { id: "pc2", prompt: "La tension aux bornes d’un fil idéal en régime simple… schéma collège : on compare souvent à :", options: ["0 V si fil parfait court", "220 V partout", "infini"], correct: 0 },
      { id: "pc3", prompt: "Un conducteur ohmique : la tension et l’intensité vérifient en général :", options: ["U = R I (loi d’Ohm)", "U = I/R toujours", "P = m g h"], correct: 0 },
      { id: "pc4", prompt: "L’effet Joule produit :", options: ["de la chaleur via courant", "de la lumière sans courant", "du vide"], correct: 0 },
      { id: "pc5", prompt: "Interrupteur ouvert : le circuit est :", options: ["fermé", "ouvert (pas de courant continu simple)", "toujours en court-circuit"], correct: 1 },
    ],
  },
  {
    id: "seed-fill-svt-college",
    title: "SVT — Collège · digestion et enzymes (repères)",
    matiere: "SVT",
    niveau: "Collège",
    chapitre: "Nutrition · enzymes",
    questions: [
      { id: "sc1", prompt: "L’amylase salivaire commence à digérer :", options: ["les lipides", "l’amidon", "l’ADN"], correct: 1 },
      { id: "sc2", prompt: "Le chyme quitte l’estomac vers :", options: ["l’intestin grêle", "le poumon", "le rein direct"], correct: 0 },
      { id: "sc3", prompt: "La bile (foie/voies biliaires) aide surtout à :", options: ["émulsionner les graisses", "fixer l’oxyde nitreux", "digérer l’ADN nucléaire seul"], correct: 0 },
      { id: "sc4", prompt: "Les villosités intestinales augmentent :", options: ["la surface d’absorption", "le volume de l’estomac seul", "la température du cerveau"], correct: 0 },
      { id: "sc5", prompt: "Une enzyme est en général :", options: ["une protéode catalytique", "un lipide stocké", "un acide nucléique ribosomal seul"], correct: 0 },
    ],
  },
  {
    id: "seed-fill-hg-lycee",
    title: "Histoire-Géographie — Lycée · gouvernance mondiale et écarts (repères)",
    matiere: "Histoire-Géographie",
    niveau: "Lycée",
    chapitre: "Institutions · inégalités",
    questions: [
      { id: "hl1", prompt: "Nations Unies : siège principal du secrétariat (classique) :", options: ["New York", "Genève seule", "Le Caire"], correct: 0 },
      { id: "hl2", prompt: "L’OMC joue un rôle dans :", options: ["le commerce international", "le permis de conduire local", "les alliances nuptiales"], correct: 0 },
      { id: "hl3", prompt: "Dette extérieure : indicateur lié à :", options: ["les échanges / finance internationale", "la température locale", "l’âge moyen du foot"], correct: 0 },
      { id: "hl4", prompt: "IDH (ONU) combine des dimensions :", options: ["santé, éducation, niveau de vie (simplifié)", "météo seule", "population urbaine brute"], correct: 0 },
      { id: "hl5", prompt: "Migrations qualifiées « fuite des cerveaux » : effet souvent décrit :", options: ["perte de compétences pour le pays d’origine", "richesse automatique pour tous", "fin du commerce"], correct: 0 },
    ],
  },
];
